### ISSUE TITLE
Markes without snippet and label.

### ISSUE THREAD

**Issue by tiagoMaua** [googlemaps/google-maps-ios-utils#12]
When i try show infowindow, i be using the method:

- (BOOL)mapView:(GMSMapView *)mapView didTapMarker:(GMSMarker *)marker {
    _mapView.selectedMarker = marker;
    return YES;
}

 But this not show nothing.

 In debug i can add the title label and snippet, like imagem below:
![captura de tela 2015-09-02 as 02 23 44](https://cloud.githubusercontent.com/assets/3158966/9623660/57b2233a-511a-11e5-9a2a-f4f446a02c42.png)

But when method mapView:didTapMarker is called, this receive a marker only position, without the title and snippet, like image below:

![captura de tela 2015-09-02 as 02 25 39](https://cloud.githubusercontent.com/assets/3158966/9623668/81012c68-511a-11e5-81c2-6f578946d702.png)

How can show Infowindow?

**Comment by hytzxd** [comment]
Thank you very much.
Thanks to you I took a task about The map.

**Comment by domesticmouse** [comment]
I'm confused. I don't believe there is a cluster manager in this code base.

**Comment by RomanSlyepko** [comment]
I've faced the same issue. But luckily I managed to create a workaround:
Your marker must have property `userData` set to the object you want the represent with `GMSMarker` (for example, `Spot`), therefore your protocol method `marker` for the `Spot` should look smth like this:
```
- (GMSMarker *)marker {
    GMSMarker *marker = [GMSMarker markerWithPosition:self.coordinates];
    marker.title = self.name;
    marker.userData = self;
    return marker;
}
```
Since userData doesn't (somehow) become nil, you can extract the object from it and set its name to the marker:
```
- (BOOL)mapView:(GMSMapView *)mapView didTapMarker:(GMSMarker *)marker {
    Spot* mySpot = marker.userData;
    marker.title = mySpot.name;
    [self.googleMapView setSelectedMarker:marker];
    return YES;
}
```
That's all! Hope that helps
