### ISSUE TITLE
Heatmap not rendered

### ISSUE THREAD

**Issue by azyet22** [googlemaps/google-maps-ios-utils#143]
After following the instructions in https://developers.google.com/maps/documentation/ios-sdk/utility/heatmap on adding heatmaps, the heatmap was not rendered on the map. There were no errors.

**Comment by domesticmouse** [comment]
Any chance of uploading your sample to GitHub so I can have a look?

**Comment by azyet22** [comment]
Hi domestic mouse. It's actually working but it seems the intensity is pretty low, barely visible. I set the intensity to 1 which I believe is the highest. 

                          if let arrivals = object["Arrivals"] as? [AnyObject] {
                                for item in arrivals {
                                    let lat = item["Latitude"] as! Double
                                    let lng = item["Longitude"] as! Double
                                    let coord = CLLocationCoordinate2DMake(lat, lng)
                                    let coords = GMUWeightedLatLng(coordinate: coord, intensity: 1.0)
                                    list.append(coords)
                                }
                            } else {
                                print("Could not read the JSON.")
                            }
                            // Add the latlngs to the heatmap layer.
                            self.heatmapLayer.weightedData = list
                            self.heatmapLayer.map = self.mapView

I'm not sure what I'm doing wrong here.

**Comment by Tilps** [comment]
Intensity property of WeightedLatLng is purely relative - it just makes the effect of one point worth more than the effect of another.  The final heatmap is normalized, so changing the intensity of all points  from one value to a different value has no effect.  (You can choose any value you like, 1.0 definitely is not the maximum.)
The heatmap's implementation makes some assumptions about the zoom ranges at which it is going to be viewed at.  Once you get past zoom 10 the inputs to the intensity to color mapping will get weaker with each  with each zoom rather than trying to re-normalize as the zoom changes.  This zoom 10 limit is artificial and if your data set is highly localized it is probably a poor choice.  At some point renormalization is going to start behaving poorly if the buckets are smaller than the average point separation.
Making the min and max zooms for renormalization configurable on a per-instance basis rather than static constants probably would be a useful future feature.
Also it might make sense to expose calculateIntensities to sub-classing to allow more advanced customization of mapping of input intensity sums to normalized intensity inputs that are used by the color mapping.

**Comment by arriolac** [comment]
I just tested our sample here and was able to see a heatmap rendered: https://github.com/googlemaps/google-maps-ios-utils/blob/master/samples/SwiftDemoApp/SwiftDemoApp/HeatmapViewController.swift

@RishabhTayal can you share more details and/or a code snippet?

**Comment by RishabhTayal** [comment]
Update: The heatmaps were actually showing. They were too small to see. Everything is good.

**Comment by RishabhTayal** [comment]
Thanks for follow up.

**Comment by chitgoks** [comment]
Just a follwup question. Did you guys get to compare the results with android-map-utils? Are the renderings the same? or not
