### ISSUE TITLE
Pass GMSMarker in GMUClusterManagerDelegate methods

### ISSUE THREAD

**Issue by arriolac** [googlemaps/google-maps-ios-utils#298]
**Is your feature request related to a problem? Please describe.**
When one of the methods in `GMUClusterManagerDelegate` is invoked, the corresponding `GMSMarker` object is not passed through which makes it difficult to map what the originating `GMSMarker` originated the click.

 **Describe the solution you'd like**
Provide a 3rd property in both methods. The new methods should have the following signature:

```objective-c
- (BOOL)clusterManager:(GMUClusterManager *)clusterManager 
                  didTapCluster:(id<GMUCluster>)cluster
                              marker:(GMSMarker *)marker;

- (BOOL)clusterManager:(GMUClusterManager *)clusterManager
           didTapClusterItem:(id<GMUClusterItem>)clusterItem
                              marker:(GMSMarker *)marker;

@end
```

 **Describe alternatives you've considered**
* Subclass `GMSMarker`
* Create a new property within `GMUClusterItem`

 **Additional context**

**Comment by amuramoto** [comment]
It appears we won't need to do this since everything falls through to `- (BOOL)mapView:(GMSMapView *)mapView didTapMarker:(GMSMarker *)marker` but we a major issue IMO is that there's no way to pass instances of `GMSMarker` to the clusterer (even though the cluster manager uses this to implement `GMUCluster` and `GMUClusterItem`. 

Probably the most straightforward way to do this is to add an `addMarker` method on cluster manager, since we can't overload the existing `addItem` method that takes `GMUClusterItem`.
