### ISSUE TITLE
GoogleMaps is not running in iOS simulator for Apple Mac M1

### ISSUE THREAD

**Issue by mamunabcoder** [googlemaps/google-maps-ios-utils#388]
Error
*****
ld: building for iOS Simulator, but linking in object file built for iOS, file '/Users/bjit/Work/JASMY/SRC/p1340_project_corona/NNForwarder/ios/Pods/GoogleMaps/Base/Frameworks/GoogleMaps.framework/GoogleMaps' for architecture arm64

I am using Xcode 13.1 Xcode to build and run the app in Simulator iPhone 11 pro

**Comment by arriolac** [comment]
For building on an M1 Mac, use the XCFramework available [here](https://developers.google.com/maps/documentation/ios-sdk/start#install-the-xcframework).

**Comment by mamunabcoder** [comment]
> here

I am using cocoa pods to install GoogleMaps in react native iOS project and Its pod based dependency installer based project. 

How could I solved this using cocoa pods dependencies installer in react native project?

**Comment by arriolac** [comment]
CocoaPods is not a supported package manager yet for XCFrameworks. You would have to use either Carthage or install the xcframework manually.

**Comment by mamunabcoder** [comment]
> CocoaPods is not a supported package manager yet for XCFrameworks. You would have to use either Carthage or install the xcframework manually.

I think, you should not understand my above question. Please try to understand

**Comment by mamunabcoder** [comment]
Why you close the bug?

**Comment by arriolac** [comment]
This bug was closed because a solution is available for M1 machines by using the [XCFramework](https://developers.google.com/maps/documentation/ios-sdk/start#install-the-xcframework) version of the SDK. At the moment, only Carthage and installing it manually are the only installation options for this. As I mentioned in my previous comment, CocoaPods is not supported for XCFrameworks. If you would like to, please file a feature request for CocoaPods support in your [public issue tracker](https://developers.google.com/maps/documentation/ios-sdk/start#install-the-xcframework).

**Comment by shawarmaz** [comment]
is this still the case? @arriolac
