### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by trant** [googlemaps/google-maps-ios-utils#48]
Hi there. I have implemented the clustering on my app but the CPU usage has gone pretty bad. I get sometimes 130% for just scrolling. I have something like 100 markers but even when I zoom in to just a few I still get high CPU usage which does not happening if I remove the clustering at all. I am clustering everytime the user moves the map a bit (maybe there is a better way of doing it?)

**Comment by mountainvat** [comment]
The cluster manager should handle camera movement events automatically for you and choose when appropriate to re-cluster. You do not need to re-cluster yourself. If you re-cluster on every single camera move I can see why the CPU is high.

**Comment by trant** [comment]
I have removed the re-cluster on camera handle but whenever I move the map I still get high CPU spikes. I noticed that willRenderMarker keeps getting called several times.

**Comment by mountainvat** [comment]
When you move the map, new markers maybe added if they become visible and before they are added willRenderMarker will be called if the GMUMarkerRendererDelegate delegate implements it. Did you implement the willRenderMarker method? It is supposed to be fast otherwise it will interfere with the rendering.

**Comment by trant** [comment]
Yes I implemented that method. In theory my points on the map will never move so the clustering could only be done once, what I need to update sometimes is the marker icon with the updated info accordingly to the app state. 

![image](https://cloud.githubusercontent.com/assets/544342/19303595/33588772-9061-11e6-998d-9ee34289b438.png)

**Comment by mountainvat** [comment]
The code looks fine to me as item.iconImage is already in memory so marker.icon = item.iconImage should be fast unless the iconImage's size is huge.

I you are still stuck, I am happy to look at a repro project.

FYI: you donot need to set marker.tracksViewChanges because you are not using the iconView property.

**Comment by trant** [comment]
So how do you refresh the icons without having to cluster them again? Do you have to remove the items and re-addd them all?


Regards



________________________________
De: Son Nguyen <notifications@github.com>
Enviado: quarta-feira, 12 de outubro de 2016 23:24
Para: googlemaps/google-maps-ios-utils
Cc: Antonio Pinho; Author
Assunto: Re: [googlemaps/google-maps-ios-utils] High CPU usage (#48)


The code looks fine to me as item.iconImage is already in memory so marker.icon = item.iconImage should be fast unless the iconImage's size is huge.

I you are still stuck, I am happy to look at a repro project.

FYI: you donot need to set marker.tracksViewChanges because you are not using the iconView property.

-

**Comment by mountainvat** [comment]
I'd suggest you use a dynamic icon using the GMSMarker.iconView property: https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_marker.html#ab16a10487ace24ac36e96eea7efb77c7

Using this property you'll need to have tracksViewChanges to YES for it to refresh/update.

**Comment by trant** [comment]
With the dynamic icon I have the same problem. How do I get the marker reference after they are on the map? If I could get marker by id or something and change its image! That would be perfect

**Comment by mountainvat** [comment]
I'd imagine you would have to associate your cluster item with the marker in a dictionary somehow. Then you have a willRenderMarker event you will have access to a marker and the marker.userData is either a id<GMUClusterItem> or a id<GMUCluster>. You can use those information to build up a map from id<GMUClusterItem> to GMSMarker.

**Comment by malavagile** [comment]
Hello @mountainvat,

I did use iconView for cluster and marker but it uses huge memory and CPU.

In Icon view, I am loading images of the user for cluster and marker. Since I am adding images, I have to keep the trackViewChanges property true otherwise it's not reflecting the image downloaded from the server on the map. If I keep turn on the property It takes a huge amount of CPU.

Can you help me out here?

Thanks,
Malav Soni

**Comment by mountainvat** [comment]
Using iconView with tracksViewChanges enabled is very expensive since the view needs to be rendered continuously into a bitmap. If your image does not change can you try to download it first and use the normal .icon property?

**Comment by malavagile** [comment]
> Using iconView with tracksViewChanges enabled is very expensive since the view needs to be rendered continuously into a bitmap. If your image does not change can you try to download it first and use the normal .icon property?

But what if I have many user's data coming from API so first I need to download the image of each of them and then add markers on the map?

Is there any other way to do it?
