### ISSUE TITLE
Correctly handle clustering identically placed items

### ISSUE THREAD

**Issue by kwstasna** [googlemaps/google-maps-ios-utils#62]
Hello.
I have 10 pins on the same latitude and longitude.
When i zoom i see only 1 pin. 
Could we make it see all of the pins in a circle for example?

**Comment by mountainvat** [comment]
You can override the GMUDefaultClusterRenderer's shouldRenderAsCluster:atZoom method to have some custom logic to return YES for that case? The easiest, but naive, way is to always return YES so that close items are always grouped into a cluster no matter how many there are or what zoom level it is.

**Comment by kwstasna** [comment]
@mountainvat   And if I have a infobox for each pin that i want my users to see when they tap on a pin?
I think you have to update the library to consider this case too.
A nice working and good example is the following

http://blog.mastermaps.com/2014/06/showing-instagram-photos-and-videos-on.html

where you can see on the top right clustered images when you zoom in and you tap, both of the images appear.

**Comment by buithuyen** [comment]
I have a same problem. How can I do this
<img width="487" alt="screen shot 2016-12-25 at 3 29 20 pm" src="https://cloud.githubusercontent.com/assets/5087522/21470348/10e7a9a8-cab7-11e6-98b5-e61a629c91a3.png">

**Comment by mountainvat** [comment]
Hi there,  I am just confirming that you want to receive the normal info window events for a cluster marker?
```
- (UIView *GMS_NULLABLE_PTR)mapView:(GMSMapView *)mapView markerInfoWindow:(GMSMarker *)marker;
- (UIView *GMS_NULLABLE_PTR)mapView:(GMSMapView *)mapView markerInfoContents:(GMSMarker *)marker;
```

With these events you can construct a custom info window for the cluster marker using the contents of its userData property.

**Comment by kwstasna** [comment]
@mountainvat Excuse me, but this is the other guys issue. @buithuyen  You should open your own issue.

For my problem, there are 10 simple markers [https://cdn.pixabay.com/photo/2014/04/03/10/03/google-309740_640.png](example) on the same lat - lon. Not 1 cluster marker. 

How can we fix it like the blog post that i posted above?

**Comment by mountainvat** [comment]
@kwstasna I do not see a straightforward solution to the problem you're solving.
Can you preprocess the points so that they do not have the exact same lat,long but slightly different? Then you can use the clustering library out of the box.

@buithuyen may be you are interested in watching this ticket https://github.com/googlemaps/google-maps-ios-utils/issues/63?

**Comment by nitisha1** [comment]
@kwstasna - i'm facing same issue.Did you find any solution?

**Comment by kwstasna** [comment]
@nitisha1 Nope. I'm currently working on other project so i dont have time.
Although i think that setting up the location of the pin in slightly different lat/long is a solution, as @mountainvat  mentioned above, although it could be better !

**Comment by domesticmouse** [comment]
Updating the title to reflect current requirement

**Comment by MaeseppTarvo** [comment]
I need the same solution. I also have multiple markers with exact same location and would like to see them in circle or somehting. And the suggested #63 ticket is not even related to that issue which was suggested by @mountainvat .
