### ISSUE TITLE
10 pins less in the map then total locations count

### ISSUE THREAD

**Issue by iosdevuz** [googlemaps/google-maps-ios-utils#80]
Hi. I am using Google-Maps-iOS-Utils. And now i have like this error: from server I am taking "N" locations.  In the map the amount of the clusters' title numbers is (N-10). I can not find where is my mistake?

**Comment by mountainvat** [comment]
The number on the cluster marker icon is a rounded number so may not be the exact "N". For example a cluster marker can show 100+ for **over** 100 items, not exactly 100 items. Only clusters smaller than the last grouping (10 by default) will show the exact item count.
Hope that makes sense.

**Comment by iosdevuz** [comment]
Hello, Thanks for replying me. I was changed the rounded numbers at here:

![2017-02-24 19 33 47](https://cloud.githubusercontent.com/assets/23485970/23307132/392d1f9c-fac8-11e6-94fe-ee4389c903e2.png)

Because i need the exact numbers of markers as a title of clusters. I can not find other way. So changed the minimum amount of markers in clusters. Can you tell me please how can i show the exact numbers of markers as a title of clusters. 

And also i have to make like this action: If user make a tap to any cluster then the markers and inside clusters must be shown and fit to screen size. 

Thanks :)

**Comment by mountainvat** [comment]
It is probably OK to increase the minimum bucket size but you will need to keep watching the memory usage because you can potentially have 1000 icons cached in memory. If you see memory usage to be a problem you can override the GMUDefaultClusterIconGenerator and tweak the NSCache _iconCache object.

For your 2nd point you can calculate the bounds of the tapped cluster and use GMSCameraUpdate's fitBounds (https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_camera_update.html#aa5b05606808272f9054c54af6830df3e) to achieve that behaviour.

**Comment by iosdevuz** [comment]
Thanks for such a like useful utils
