### ISSUE TITLE
Carthage support request

### ISSUE THREAD

**Issue by AAverin** [googlemaps/google-maps-ios-utils#99]
Would be great to have carthage support
At the moment I get
```
Dependency "google-maps-ios-utils" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/googlemaps/google-maps-ios-utils/issues/new
```

or

```
Skipped building google-maps-ios-utils due to the error:
Dependency "google-maps-ios-utils" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/googlemaps/google-maps-ios-utils/issues/new
```

**Comment by domesticmouse** [comment]
Please feel free to create a Pull Request with the required changes to support Carthage.

**Comment by AAverin** [comment]
Also, dynamic frameworks are needed: https://github.com/Carthage/Carthage

**Comment by domesticmouse** [comment]
Please feel free to create an issue on the [Google Maps SDK for iOS issue tracker](https://developers.google.com/maps/documentation/ios-sdk/support#issue-tracker) about the dynamic frameworks issue. We are no longer supporting iOS 7, so that change should now be feasible.

As for Carthage support for both Google Maps SDK for iOS and the Google Maps iOS Utils, please feel free to submit pull requests with the required changes. CocoaPods support for Google Maps SDK for iOS started out as a community supported feature that we adopted and built out internal infrastructure support across all of our iOS APIs.

Thanks!

**Comment by carlosmolano** [comment]
https://github.com/leoneparise/GoogleMaps-Carthage

**Comment by arriolac** [comment]
This is now supported. See [Carthhage.md](https://github.com/googlemaps/google-maps-ios-utils/blob/master/Carthage.md).
